In [1]:
# importamos librerias
import pandas as pd
import numpy as np

In [3]:
# Paso 1: Leer el archivo CSV original
df_original = pd.read_csv('emails_pre.csv')
df_original
# columnas
# blue,green,red,label

,0,0.1,1,0.2,0.3,0.4,2,0.5,0.6,0.7,...,0.2957,0.2958,0.2959,0.2960,0.2961,0.2962,0.2963,0.2964,0.2965,0.2966
0,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,1,0,0
1,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
2,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
3,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,1,0,0
4,4,5,1,4,2,3,45,1,0,16,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5167,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,1,0,0
5168,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,1
5169,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,1,0,1
5170,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [4]:
def aumentar_ejemplos(archivo_original, archivo_aumentado, num_ejemplos_deseados):
    # Paso 1: Leer el archivo CSV original
    df_original = pd.read_csv(archivo_original)
    
    # Paso 2: Calcular la media de cada par de ejemplos
    df_medias = (df_original.shift() + df_original) / 2
    
    # Paso 3: Reemplazar los valores no finitos con un valor predeterminado
    df_medias = df_medias.replace([np.inf, -np.inf], np.nan).fillna(0)
    
    # Paso 4: Redondear y convertir a enteros
    df_medias = df_medias.round(decimals=0).astype(int)
    
    # Paso 5: Calcular la diferencia entre el nÃºmero deseado de ejemplos y los ejemplos originales
    diff = num_ejemplos_deseados - len(df_medias)
    
    # Paso 6: Generar ejemplos adicionales seleccionando aleatoriamente los ejemplos originales
    if diff > 0:
        indices_muestreo = np.random.choice(df_medias.index, size=diff, replace=True)
        ejemplos_adicionales = df_medias.iloc[indices_muestreo]
        df_medias = pd.concat([df_medias, ejemplos_adicionales], ignore_index=True)
    
    # Paso 7: Guardar los nuevos ejemplos en un nuevo archivo CSV
    df_medias[:num_ejemplos_deseados].to_csv(archivo_aumentado, index=False)

# Uso de la funciÃ³n
aumentar_ejemplos('emails_pre.csv', 'emails_pre.csv', 10000)

In [6]:
df_aumentado = pd.read_csv('emails_pre.csv')
df_aumentado

,0,0.1,1,0.2,0.3,0.4,2,0.5,0.6,0.7,...,0.2957,0.2958,0.2959,0.2960,0.2961,0.2962,0.2963,0.2964,0.2965,0.2966
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4,6,12,3,3,1,55,0,14,11,...,0,0,0,0,0,0,0,0,0,0
2,0,2,12,0,2,0,30,1,5,2,...,0,0,0,0,0,0,0,0,0,0
3,4,6,20,0,5,2,54,1,10,2,...,0,0,0,0,0,0,0,0,0,0
4,6,6,9,2,4,2,51,0,4,10,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,1,2,0,0,0,13,0,1,5,...,0,0,0,0,0,0,0,0,0,0
9996,35,26,8,21,12,24,252,6,0,77,...,0,0,0,0,0,0,0,5,0,1
9997,2,2,1,0,0,0,11,0,0,2,...,0,0,0,0,0,0,0,0,0,0
9998,20,12,2,4,6,2,85,4,1,20,...,0,0,0,0,0,0,0,0,0,0
9999,1,1,2,2,0,1,42,0,0,9,...,0,0,0,0,0,0,0,0,0,0