In [31]:
import pandas as pd
import csv
import numpy as np

In [24]:
# cargar a una variable el dataset
df = pd.read_csv("datasets/dataset-tortuga.csv")
df

,Unnamed: 0,NAME,USER_ID,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
0,28,Stormy Muto,58283940,7.0,39.0,29.0,2.0,4.0,0.0,2.0,5.0,0.0,84.0,74.0,NaN,beginner_front_end
1,81,Carlos Ferro,1357218,32.0,0.0,44.0,2.0,0.0,0.0,0.0,5.0,0.0,67.0,45.0,NaN,beginner_front_end
2,89,Robby Constantini,63212105,45.0,0.0,59.0,0.0,5.0,4.0,0.0,4.0,1.0,NaN,54.0,47.0,advanced_front_end
3,138,Paul Mckenny,23239851,36.0,19.0,28.0,0.0,5.0,7.0,0.0,5.0,3.0,NaN,71.0,89.0,beginner_data_science
4,143,Jean Webb,72234478,61.0,78.0,38.0,6.0,11.0,0.0,4.0,3.0,0.0,66.0,85.0,NaN,advanced_front_end
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20495,Rose Jurado,66754730,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,advanced_backend
19996,20496,Johnny Jones,6874888,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,advanced_front_end
19997,20497,Lawrence Givens,83752787,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,advanced_backend
19998,20498,Betty Diclaudio,45806698,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,advanced_front_end
19999,20499,Connie Harper,67068866,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,advanced_data_science

In [25]:
columnas_a_eliminar = ['NAME', 'USER_ID']
df = df.drop(columnas_a_eliminar, axis=1)

# Guardar el DataFrame resultante en un nuevo archivo CSV
df.to_csv('tortuga_pre.csv', index=False)

In [26]:
df

,Unnamed: 0,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
0,28,7.0,39.0,29.0,2.0,4.0,0.0,2.0,5.0,0.0,84.0,74.0,NaN,beginner_front_end
1,81,32.0,0.0,44.0,2.0,0.0,0.0,0.0,5.0,0.0,67.0,45.0,NaN,beginner_front_end
2,89,45.0,0.0,59.0,0.0,5.0,4.0,0.0,4.0,1.0,NaN,54.0,47.0,advanced_front_end
3,138,36.0,19.0,28.0,0.0,5.0,7.0,0.0,5.0,3.0,NaN,71.0,89.0,beginner_data_science
4,143,61.0,78.0,38.0,6.0,11.0,0.0,4.0,3.0,0.0,66.0,85.0,NaN,advanced_front_end
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20495,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,advanced_backend
19996,20496,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,advanced_front_end
19997,20497,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,advanced_backend
19998,20498,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,advanced_front_end
19999,20499,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,advanced_data_science

In [27]:
# mapeo de la columna PROFILE
# - beginner_front_end =1
# - advanced_front_end =2
# - beginner_back_end =3
# - advanced_back_end =4
# - beginner_data_science =5
# - advanced_data_science =6
mapeo_profile = {'beginner_front_end': 1, 'advanced_front_end': 2, 'beginner_backend': 3, 'advanced_backend': 4, 'beginner_data_science': 5, 'advanced_data_science': 6}

df['PROFILE'] = df['PROFILE'].map(mapeo_profile)

datos = df
datos.to_csv('tortuga_pre.csv', index=False)

In [30]:
set(datos['PROFILE'].tolist())

{1, 2, 3, 4, 5, 6}

In [34]:
datos = datos.fillna(0)

datos.to_csv('tortuga_pre.csv', index=False)

In [35]:
datos

,Unnamed: 0,HOURS_DATASCIENCE,HOURS_BACKEND,HOURS_FRONTEND,NUM_COURSES_BEGINNER_DATASCIENCE,NUM_COURSES_BEGINNER_BACKEND,NUM_COURSES_BEGINNER_FRONTEND,NUM_COURSES_ADVANCED_DATASCIENCE,NUM_COURSES_ADVANCED_BACKEND,NUM_COURSES_ADVANCED_FRONTEND,AVG_SCORE_DATASCIENCE,AVG_SCORE_BACKEND,AVG_SCORE_FRONTEND,PROFILE
0,28,7.0,39.0,29.0,2.0,4.0,0.0,2.0,5.0,0.0,84.0,74.0,0.0,1
1,81,32.0,0.0,44.0,2.0,0.0,0.0,0.0,5.0,0.0,67.0,45.0,0.0,1
2,89,45.0,0.0,59.0,0.0,5.0,4.0,0.0,4.0,1.0,0.0,54.0,47.0,2
3,138,36.0,19.0,28.0,0.0,5.0,7.0,0.0,5.0,3.0,0.0,71.0,89.0,5
4,143,61.0,78.0,38.0,6.0,11.0,0.0,4.0,3.0,0.0,66.0,85.0,0.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20495,0.0,44.0,42.0,8.0,4.0,7.0,3.0,3.0,3.0,74.0,73.0,93.0,4
19996,20496,0.0,85.0,63.0,3.0,5.0,0.0,4.0,7.0,3.0,50.0,83.0,94.0,2
19997,20497,32.0,50.0,22.0,0.0,4.0,0.0,6.0,2.0,3.0,61.0,81.0,75.0,4
19998,20498,0.0,96.0,69.0,3.0,3.0,3.0,5.0,7.0,4.0,64.0,68.0,68.0,2
19999,20499,51.0,24.0,36.0,4.0,2.0,7.0,0.0,0.0,2.0,63.0,61.0,87.0,6

In [32]:
df = datos
# Read the CSV file into a DataFrame
df = pd.read_csv('tortuga_pre.csv')

# Define the augmentation operations
# Here, we will add noise to the data
noise = np.random.normal(0, 0.1, df.shape)

# Apply the augmentation operations
df += noise

# Define the desired size of the example
desired_size = 50000

# Create a new DataFrame with the desired size
augmented_df = pd.DataFrame()

# While the size of the augmented DataFrame is less than the desired size,
# add new rows to the DataFrame
while len(augmented_df) < desired_size:
    # Randomly select a row from the original DataFrame
    row = df.sample(1)

    # Add the row to the augmented DataFrame
    augmented_df = augmented_df.append(row)

# Write the augmented DataFrame to a new CSV file
augmented_df.to_csv('tortuga_pre1.csv', index=False)

AttributeError: 'DataFrame' object has no attribute 'append'

In [74]:
# Obtener el Ã­ndice de la columna
indice_columna = df.columns.get_loc('Age')

# Obtener el nombre de todas las columnas excepto la que se va a mover
columnas_sin_mover = [col for col in df.columns if col != 'Age']

# Reorganizar las columnas en el orden deseado
nuevo_orden_columnas = columnas_sin_mover + ['Age']
df = df[nuevo_orden_columnas]

# Guardar el DataFrame actualizado en un nuevo archivo CSV
df.to_csv('sleep_healt_pre.csv', index=False)

In [75]:
df

,Gender,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Age
0,1,6.1,6,42,6,77,4200,27
1,1,6.2,6,60,8,75,10000,28
2,1,6.2,6,60,8,75,10000,28
3,1,5.9,4,30,8,85,3000,28
4,1,5.9,4,30,8,85,3000,28
...,...,...,...,...,...,...,...,...
369,2,8.1,9,75,3,68,7000,59
370,2,8.0,9,75,3,68,7000,59
371,2,8.1,9,75,3,68,7000,59
372,2,8.1,9,75,3,68,7000,59
373,2,8.1,9,75,3,68,7000,59

In [76]:
df = pd.read_csv("datos_aumentados.csv")
# Reindexar el DataFrame
df = df.reset_index(drop=True)
# Calcular el factor de interpolaciÃ³n
factor_interpolacion = 10  # (200 ejemplos / 50 ejemplos)

# Crear una lista vacÃ­a para almacenar los DataFrames interpolados
df_interpolados = []

# Iterar sobre cada columna del DataFrame
for columna in df.columns:
    # Interpolar los valores de la columna y expandir el DataFrame
    columna_interpolada = df[columna].interpolate().repeat(factor_interpolacion)
    df_interpolados.append(columna_interpolada)

# Concatenar las columnas interpoladas en un nuevo DataFrame aumentado
df_aumentado = pd.concat(df_interpolados, axis=1)

FileNotFoundError: [Errno 2] No such file or directory: 'datos_aumentados.csv'

In [ ]:
# Verificar el DataFrame aumentado
print(df_aumentado)

      1  6.1  6  42  6.2  77  4200  27
0     1  6.1  6  42    6  77  4200  27
0     1  6.1  6  42    6  77  4200  27
0     1  6.1  6  42    6  77  4200  27
0     1  6.1  6  42    6  77  4200  27
0     1  6.1  6  42    6  77  4200  27
...  ..  ... ..  ..  ...  ..   ...  ..
1868  2  8.1  9  75    3  68  7000  59
1868  2  8.1  9  75    3  68  7000  59
1868  2  8.1  9  75    3  68  7000  59
1868  2  8.1  9  75    3  68  7000  59
1868  2  8.1  9  75    3  68  7000  59

[18690 rows x 8 columns]